plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.testng:testng:7.1.0'
}

test {
    useTestNG()

    // Для отладки
    testLogging {
        events "PASSED", "SKIPPED", "FAILED", "STANDARD_OUT", "STANDARD_ERROR"
        exceptionFormat = "full"
    }

    // Явно указываем где искать тесты
    scanForTestClasses = true
    include '**/*Test.class'
}